remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 

title: [Artificial Intelligence in Medicine]
description: [A research paper about the effective worldwide implementation of AI in medicine]


